import Head from "next/head";
import { Inter } from "next/font/google";
import { Header } from "src/components/Header";
import { useCallback, useEffect, useState } from "react";
import { Posts as PostComponent } from "@/src/components/Posts";

const inter = Inter({ subsets: ["latin"] });

const Posts = (props) => {
  return (
    <>
      <Head>
        <title>Posts Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <h1 className="text-center font-bold text-4xl mb-8">投稿一覧</h1>
        <PostComponent />
      </main>
    </>
  );
};

export default Posts;
