import { fetcher } from "@/src/utils/fetcher";
import Head from "next/head";
import "src/styles/globals.css";
import { SWRConfig } from "swr";

const App = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SWRConfig value={{ fetcher: fetcher }}>
        <Component {...pageProps} />
      </SWRConfig>
    </>
  );
};

export default App;
