import Head from "next/head";
import { Inter } from "next/font/google";
// import styles from '@/styles/Home.module.css'
import { Main } from "src/components/Main";
import { Header } from "src/components/Header";
import classes from "src/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function About({
  isShow,
  doubleCount,
  handleClick,
  handleDisplay,
  text,
  array,
  handleChange,
  handleAdd,
}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div className={classes.content}>
        <p>{isShow ? doubleCount : null}</p>
        <button onClick={handleClick}>カウントアップ</button>
        <button onClick={() => handleDisplay()}>{isShow ? "非表示" : "表示"}</button>

        <div className={classes.textAdd}>
          <input type="text" value={text} onChange={(e) => handleChange(e)} />
          <button onClick={handleAdd}>Add</button>
          <ul>
            {array.map((item) => {
              return <li key={item}>{item}</li>;
            })}
          </ul>
        </div>
      </div>

      <Main page="about" />
    </>
  );
}
