import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
// import styles from '@/styles/Home.module.css'
import { Links } from "src/components/Links";
import { Main } from "src/components/Main";
import { Header } from "src/components/Header";
import { useCallback, useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [count, setCount] = useState(1);
  const [text, setText] = useState("");
  const [isShow, setIsShow] = useState(true);
  const [array, setArray] = useState([]);

  const handleDisplay = useCallback(() => {
    setIsShow((prevIsShow) => !prevIsShow);
  }, []);

  const handleClick = useCallback(() => {
    // setCount(count + 1);　NG例
    // setCount(function (count) {
    //   return count + 1;
    // });
    // ↓　↓　↓
    setCount((prevCount) => prevCount + 1);
  }, [count]);

  const handleChange = useCallback((e) => {
    setText(e.target.value);
  }, []);

  const handleAdd = useCallback(() => {
    setArray((prevArray) => {
      if (prevArray.some((item) => item === text)) {
        alert("同じアイテムが存在します");
        return prevArray;
      }
      return [...prevArray, text];
    });
  }, [text]);

  useEffect(() => {
    // Mount時の処理
    // document.body.style.backgroundColor = "lightblue";

    // Unmount時の処理
    return () => {
      // document.body.style.backgroundColor = "";
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <div>
        <p>{isShow ? count : null}</p>
        <button onClick={handleClick}>ボタン</button>
        <button onClick={() => handleDisplay()}>{isShow ? "非表示" : "表示"}</button>
      </div>

      <div>
        <input type="text" value={text} onChange={(e) => handleChange(e)} />
        <button onClick={handleAdd}>Add</button>
        <ul>
          {array.map((item) => {
            return <li key={item}>{item}</li>;
          })}
        </ul>
      </div>
      <Main page="index" />
    </>
  );
}
