import Head from "next/head";
import { Inter } from "next/font/google";
import { Header } from "src/components/Header";
import classes from "src/components/Layout/Layout.module.css";
import { Layout } from "@/src/components/Layout";

const inter = Inter({ subsets: ["latin"] });

export default function Index() {
  return (
    <>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Layout>
          <h1 className={classes.pageTitle}>Next.jsで学ぶReact講座</h1>
        </Layout>
      </main>
    </>
  );
}
