import Head from "next/head";
import { useRouter } from "next/router";
import { Header } from "src/components/Header";

const PostId = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {router.query.id}
    </>
  );
};

export default PostId;
